/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AdminImport } from './routes/_admin'
import { Route as IndexImport } from './routes/index'
import { Route as UsersIndexImport } from './routes/users/index'
import { Route as ContentIndexImport } from './routes/content/index'
import { Route as UsersIdImport } from './routes/users/$id'
import { Route as ContentNewImport } from './routes/content/new'
import { Route as ContentIdImport } from './routes/content/$id'
import { Route as AdminPanelImport } from './routes/_admin/panel'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/_admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIndexRoute = UsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const ContentIndexRoute = ContentIndexImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => rootRoute,
} as any)

const UsersIdRoute = UsersIdImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRoute,
} as any)

const ContentNewRoute = ContentNewImport.update({
  id: '/content/new',
  path: '/content/new',
  getParentRoute: () => rootRoute,
} as any)

const ContentIdRoute = ContentIdImport.update({
  id: '/content/$id',
  path: '/content/$id',
  getParentRoute: () => rootRoute,
} as any)

const AdminPanelRoute = AdminPanelImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_admin/panel': {
      id: '/_admin/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AdminPanelImport
      parentRoute: typeof AdminImport
    }
    '/content/$id': {
      id: '/content/$id'
      path: '/content/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof ContentIdImport
      parentRoute: typeof rootRoute
    }
    '/content/new': {
      id: '/content/new'
      path: '/content/new'
      fullPath: '/content/new'
      preLoaderRoute: typeof ContentNewImport
      parentRoute: typeof rootRoute
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdImport
      parentRoute: typeof rootRoute
    }
    '/content/': {
      id: '/content/'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentIndexImport
      parentRoute: typeof rootRoute
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AdminRouteChildren {
  AdminPanelRoute: typeof AdminPanelRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPanelRoute: AdminPanelRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/panel': typeof AdminPanelRoute
  '/content/$id': typeof ContentIdRoute
  '/content/new': typeof ContentNewRoute
  '/users/$id': typeof UsersIdRoute
  '/content': typeof ContentIndexRoute
  '/users': typeof UsersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/panel': typeof AdminPanelRoute
  '/content/$id': typeof ContentIdRoute
  '/content/new': typeof ContentNewRoute
  '/users/$id': typeof UsersIdRoute
  '/content': typeof ContentIndexRoute
  '/users': typeof UsersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/_admin/panel': typeof AdminPanelRoute
  '/content/$id': typeof ContentIdRoute
  '/content/new': typeof ContentNewRoute
  '/users/$id': typeof UsersIdRoute
  '/content/': typeof ContentIndexRoute
  '/users/': typeof UsersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/panel'
    | '/content/$id'
    | '/content/new'
    | '/users/$id'
    | '/content'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/panel'
    | '/content/$id'
    | '/content/new'
    | '/users/$id'
    | '/content'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/about'
    | '/_admin/panel'
    | '/content/$id'
    | '/content/new'
    | '/users/$id'
    | '/content/'
    | '/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContentIdRoute: typeof ContentIdRoute
  ContentNewRoute: typeof ContentNewRoute
  UsersIdRoute: typeof UsersIdRoute
  ContentIndexRoute: typeof ContentIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  ContentIdRoute: ContentIdRoute,
  ContentNewRoute: ContentNewRoute,
  UsersIdRoute: UsersIdRoute,
  ContentIndexRoute: ContentIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_admin",
        "/about",
        "/content/$id",
        "/content/new",
        "/users/$id",
        "/content/",
        "/users/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_admin": {
      "filePath": "_admin.tsx",
      "children": [
        "/_admin/panel"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_admin/panel": {
      "filePath": "_admin/panel.tsx",
      "parent": "/_admin"
    },
    "/content/$id": {
      "filePath": "content/$id.tsx"
    },
    "/content/new": {
      "filePath": "content/new.tsx"
    },
    "/users/$id": {
      "filePath": "users/$id.tsx"
    },
    "/content/": {
      "filePath": "content/index.tsx"
    },
    "/users/": {
      "filePath": "users/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
